# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
# services:
# - mysql:latest
# - redis:latest
# - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

build:
  image: node:latest
  stage: build
  script:
    - export NODE_OPTIONS=--max_old_space_size=8192
    - npm install
    - npm run build
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

docker:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker -v
    - docker info

  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .

test:unit:
  image: node:latest
  stage: test
  script:
    - npm run test:cov
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

test:e2e:
  image: node:latest
  stage: test
  script:
    - npm run test:e2e
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/
